# Generated by Django 3.0.2 on 2020-02-13 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0002_article_author_placeproxy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
