# Generated by Django 3.0.2 on 2020-02-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0003_remove_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ProdcutId', models.AutoField(db_column='Product Id', primary_key=True, serialize=False)),
                ('ProdcutName', models.CharField(db_column='Product Name', max_length=100)),
                ('ProdcutPrice', models.IntegerField(db_column='Product Price')),
            ],
        ),
    ]
