# Generated by Django 3.0.2 on 2020-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practiceapp', '0004_productmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(db_column='Body', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(db_column='Description', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(db_column='Id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(db_column='Title', max_length=120),
        ),
    ]
